name: 功能建议
description: 描述需要改善的 Git 工作流
title: '[建议] '
body:
  - type: textarea
    id: problem
    attributes:
      label: 你希望解决的问题
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: 期望的操作方式
    validations:
      required: true
